### ISSUE TITLE
Environment Variables are not quite correct

### ISSUE THREAD

**Issue by sam-n-johnston** [jefer590/serverless-offline-step-functions#1]
**Describe the bug**
Each task in the step function has all the environment variables, even when it shouldn't based on the serverless.yml

**To Reproduce**
1. Create a serverless like this:
```
provider:
    environment:
        ENV_VAR_1: ${self:custom.config.env1}

functions:
    func1:
        handler: src/transfer/ui/lambdas/CreatePurchaseOrder.handler
        environment:
            ENV_VAR_2: ${self:custom.config.env2}

    func2:
        handler: src/transfer/ui/lambdas/CreatePurchaseOrder.handler
        environment:
            ENV_VAR_3: ${self:custom.config.env3}
```
2. Log the env vars in `func1` and `func2`
3. Noticed that both have all 3 environment variables

**Expected behaviour**
It should only have the environment variables defined for them. 

**Additional context**
We would need to modify the `injectEnvVars` method of `main.ts`. And it would be need evaluate before starting the next lambda.
