### ISSUE TITLE
Resource should be optional

### ISSUE THREAD

**Issue by sam-n-johnston** [jefer590/serverless-offline-step-functions#116]
**Describe the bug**
When using a map, the `Resource` is optional, but the package throws

**To Reproduce**
Create a Map 
```
stepFunctions:
  stateMachines:
    stateMachine1:
      name: stateMachine2
      definition:
        Comment: "Create test"
        StartAt: Lambda2
        States:
          Lambda2:
            Type: Task
            Resource:
              Fn::GetAtt: [lambda2, Arn]
            ResultPath: $.inboundShipmentProductsCost
            Retry:
              - ErrorEquals:
                  - States.ALL
                IntervalSeconds: 2
                MaxAttempts: 6
                BackoffRate: 1.5
            Next: Mapping
          Mapping:
            Type: Map # <<<< No Resource here!
            ItemsPath: "$.inboundShipmentProductsCost"
            Iterator:
                StartAt: Lambda3
                States:
                    Lambda3:
                        Type: Task
                        Resource:
                            Fn::GetAtt: [ lambda3, Arn ]
                        End: true
            Parameters:
                requestId.$: "$.requestId"
                inboundShipmentId.$: "$.inboundShipmentDetails.shipmentId"
                productCost.$: "$$.Map.Item.Value"
            End: true
```

Then it throws trying to do `.endsWith` on undefined

**Expected behavior**
Should work as expected
