### ISSUE TITLE
Output of step function is incorrect

### ISSUE THREAD

**Issue by sam-n-johnston** [jefer590/serverless-offline-step-functions#135]
**Describe the bug**
Output of step function is incorrect

**To Reproduce**
Create a step function like so:
```
    stateMachine3:
      name: stateMachine3
      definition:
        Comment: "Create test"
        StartAt: Step1
        States:
          Step1:
            Type: Task
            Resource:
              Fn::GetAtt: [lambda2, Arn]
            ResultPath: '$.step1Details'
            Next: Step2
          Step2:
            Type: Task
            Parameters:
                requestId.$: '$.step1Details.requestId'
                inboundShipmentId.$: '$.step1Details.inboundShipmentDetails.shipmentId'
            Resource:
              Fn::GetAtt: [lambda2, Arn]
            ResultPath: '$.step2Details'
            Next: Step3
          Step3:
            Type: Task
            Parameters:
                requestId.$: '$.step1Details.requestId'
                inboundShipmentId.$: '$.step1Details.inboundShipmentDetails.shipmentId'
            Resource:
              Fn::GetAtt: [lambda3, Arn]
            End: true
```

In `Step3`, the `step1Details` don't exist. 

**Expected behavior**
They should exist
