### ISSUE TITLE
ResultPath is not working as expected

### ISSUE THREAD

**Issue by sam-n-johnston** [jefer590/serverless-offline-step-functions#16]
**Describe the bug**
The result path isn't working as expected. 

If I do something like this:
```
MyLambda:
    Type: Task
    Resource:
        Fn::GetAtt: [myLambda, Arn]
    ResultPath: '$.myPath'
    Next: SomeOtherLambda
```
It throws:
```
Error:       
    at Function.processResultPath (/code/node_modules/@fernthedev/serverless-offline-step-functions/dist/StateProcessor.js:26:19)
    at TaskExecutor.processOutput (/code/node_modules/@fernthedev/serverless-offline-step-functions/dist/stateTasks/executors/TaskExecutor.js:55:54)
    at TaskExecutor.execute (/code/node_modules/@fernthedev/serverless-offline-step-functions/dist/stateTasks/executors/TaskExecutor.js:42:33)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Expected behavior**
It should not throw and the output JSON should be like:
```
{
   previousKey: 'Previvous Value',
   myPath: "Output of the current lambda" 
}
```

**Additional context**
