### ISSUE TITLE
Choice isn't working as expected

### ISSUE THREAD

**Issue by sam-n-johnston** [jefer590/serverless-offline-step-functions#192]
**Describe the bug**
Choice isn't working as expected

**To Reproduce**
1. create a choice, like
```
        issomethingEnabled:
            Type: Choice
            Choices:
                - Variable: '$.isSomething'
                  BooleanEquals: true
                  Next: A
                - Variable: '$.isSomething'
                  BooleanEquals: false
                  Next: B
            Default: B
```
2. Run
3. See error `No NextState or Default`

**Expected behavior**
No error. Default should be used if variable is not found or doesn't exist
