### ISSUE TITLE
Env vars defined twice causes problems 

### ISSUE THREAD

**Issue by sam-n-johnston** [jefer590/serverless-offline-step-functions#53]
**Describe the bug**

Define an env var in 1 lambda and the provider. 

**To Reproduce**

```
provider:
    environment:
        ENV_1: ${self:custom.config.nodeEnv}

stepFunction:
  states:
     step1:
        ...
     step2:
        ...

function_1:
    environment:
        ENV_1: ${self:custom.config.nodeEnv}

function_2:
   {...}
```

When you get to `function_2`, `ENV_1` is missing

**Expected behavior**
When you get to `function_2`, `ENV_1` should be defiend
