### ISSUE TITLE
State machine uses key instead of name property

### ISSUE THREAD

**Issue by sam-n-johnston** [jefer590/serverless-offline-step-functions#83]
**Describe the bug**

When creating a state machine, we need to use the name in the step function definition as the key used, i.e:

**To Reproduce**
1. Create a step function with a mismatch of name and key:
```
stepFunctions:
    stateMachines:
        MyStep: 
            name: MyLocalStep
            definition:
                ...
```
2. Try to run it
3. It will hang and never respond

**Expected behavior**
It should work and use the `MyLocalStep` name

I need to confirm this in AWS, I'll edit this once I confirm.
